# Offense count: 6
# Cop supports --auto-correct.
Style/RescueModifier:
  Exclude:
    - 'app/models/bgeigie_import.rb'
    - 'app/models/drive_import.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowAsExpressionSeparator.
Style/Semicolon:
  Exclude:
    - 'spec/integration/api/bgeigie_imports_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: only_raise, only_fail, semantic
Style/SignalException:
  Exclude:
    - 'lib/tasks/boostrap.rake'

# Offense count: 4
# Cop supports --auto-correct.
Style/SpaceAfterComma:
  Exclude:
    - 'spec/integration/api/bgeigie_imports_spec.rb'
    - 'spec/integration/api/measurements_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: space, no_space
Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

# Offense count: 7
# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment.
Style/SpaceAroundOperators:
  Exclude:
    - 'app/controllers/measurements_controller.rb'
    - 'app/models/bgeigie_log.rb'
    - 'config/environments/test.rb'
    - 'config/initializers/carrierwave.rb'
    - 'db/migrate/20120521225350_add_spatial_index_on_measurements.rb'
    - 'spec/integration/api/devices_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: space, no_space
Style/SpaceBeforeBlockBraces:
  Enabled: false

# Offense count: 8
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, EnforcedStyleForEmptyBraces, SpaceBeforeBlockParameters.
# SupportedStyles: space, no_space
Style/SpaceInsideBlockBraces:
  Enabled: false

# Offense count: 6
# Cop supports --auto-correct.
Style/SpaceInsideBrackets:
  Exclude:
    - 'config/initializers/devise.rb'
    - 'db/migrate/20160208190731_add_subtype_to_measurement_imports.rb'

# Offense count: 13
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
# SupportedStyles: space, no_space
Style/SpaceInsideHashLiteralBraces:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/SpaceInsideParens:
  Exclude:
    - 'db/migrate/20130705092519_create_rails_admin_histories_table.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles.
# SupportedStyles: use_perl_names, use_english_names
Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

# Offense count: 181
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
# IgnoredMethods: respond_to, define_method
Style/SymbolProc:
  Exclude:
    - 'app/models/drive_import.rb'
    - 'db/migrate/20120307175658_add_timestamps_to_measurement_imports.rb'
    - 'spec/models/bgeigie_import_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/Tab:
  Exclude:
    - 'db/migrate/20111214154833_create_delayed_jobs.rb'

# Offense count: 37
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: final_newline, final_blank_line
Style/TrailingBlankLines:
  Enabled: false

# Offense count: 330
# Cop supports --auto-correct.
Style/TrailingWhitespace:
  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
Style/UnneededInterpolation:
  Exclude:
    - 'app/helpers/measurements_helper.rb'
    - 'app/models/drive_import.rb'
    - 'config/unicorn.rb'

# Offense count: 6
# Cop supports --auto-correct.
Style/UnneededPercentQ:
  Exclude:
    - 'app/models/bgeigie_import.rb'
    - 'app/models/drive_import.rb'

# Offense count: 2
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: snake_case, camelCase
Style/VariableName:
  Enabled: false

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles, WordRegex.
# SupportedStyles: percent, brackets
Style/WordArray:
  EnforcedStyle: percent
  MinSize: 4
