Bundler/OrderedGems:
  Enabled: false
Lint/RescueWithoutErrorClass:
  Enabled: false
Lint/ScriptPermission:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Lint/UnneededSplatExpansion:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Security/YAMLLoad:
  Enabled: false
Style/DateTime:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/IdenticalConditionalBranches:
  Enabled: false
Style/MultilineIfModifier:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Style/SymbolArray:
  Enabled: false
