# Offense count: 4
# Cop supports --auto-correct.
Style/UnneededInterpolation:
  Exclude:
    - 'app/helpers/measurements_helper.rb'
    - 'app/models/drive_import.rb'
    - 'config/unicorn.rb'

# Offense count: 6
# Cop supports --auto-correct.
Style/UnneededPercentQ:
  Exclude:
    - 'app/models/bgeigie_import.rb'
    - 'app/models/drive_import.rb'

# Offense count: 2
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: snake_case, camelCase
Style/VariableName:
  Enabled: false

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles, WordRegex.
# SupportedStyles: percent, brackets
Style/WordArray:
  EnforcedStyle: percent
  MinSize: 4
