# Offense count: 181
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
# IgnoredMethods: respond_to, define_method
Style/SymbolProc:
  Exclude:
    - 'app/models/drive_import.rb'
    - 'db/migrate/20120307175658_add_timestamps_to_measurement_imports.rb'
    - 'spec/models/bgeigie_import_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/Tab:
  Exclude:
    - 'db/migrate/20111214154833_create_delayed_jobs.rb'

# Offense count: 37
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: final_newline, final_blank_line
Style/TrailingBlankLines:
  Enabled: false

# Offense count: 330
# Cop supports --auto-correct.
Style/TrailingWhitespace:
  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
Style/UnneededInterpolation:
  Exclude:
    - 'app/helpers/measurements_helper.rb'
    - 'app/models/drive_import.rb'
    - 'config/unicorn.rb'

# Offense count: 6
# Cop supports --auto-correct.
Style/UnneededPercentQ:
  Exclude:
    - 'app/models/bgeigie_import.rb'
    - 'app/models/drive_import.rb'

# Offense count: 2
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: snake_case, camelCase
Style/VariableName:
  Enabled: false

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles, WordRegex.
# SupportedStyles: percent, brackets
Style/WordArray:
  EnforcedStyle: percent
  MinSize: 4
