inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true

Lint/BlockAlignment:
  Exclude:
    - 'db/migrate/20130705092519_create_rails_admin_histories_table.rb'

Lint/DefEndAlignment:
  Enabled: true
  Exclude:
    - 'db/migrate/20130705092519_create_rails_admin_histories_table.rb'
    - 'db/migrate/20150919060031_add_extra_fields_to_measurements_table.rb'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/20111214162214_create_bgeigie_logs.rb'
    - 'db/migrate/20120323105044_create_drive_logs.rb'

Metrics/LineLength:
  Max: 160
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/20111214154833_create_delayed_jobs.rb'
    - 'db/migrate/20111214162214_create_bgeigie_logs.rb'
    - 'db/migrate/20120323105044_create_drive_logs.rb'
    - 'db/migrate/20120418231658_devise_create_admins.rb'

Style/AccessModifierIndentation:
  EnforcedStyle: indent
