Lint/BlockAlignment:
  Exclude:
    - 'db/migrate/20130705092519_create_rails_admin_histories_table.rb'

Lint/DefEndAlignment:
  Enabled: true
  Exclude:
    - 'db/migrate/20130705092519_create_rails_admin_histories_table.rb'
    - 'db/migrate/20150919060031_add_extra_fields_to_measurements_table.rb'

# Offense count: 11
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/20111214162214_create_bgeigie_logs.rb'
    - 'db/migrate/20120323105044_create_drive_logs.rb'

# Offense count: 283
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 905

# Offense count: 13
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 22

# Offense count: 1
Metrics/PerceivedComplexity:
  Max: 23

# Offense count: 1
# Cop supports --auto-correct.
Performance/RedundantMatch:
  Exclude:
    - 'app/controllers/application_controller.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles, IndentationWidth.
# SupportedStyles: outdent, indent
Style/AccessModifierIndentation:
  EnforcedStyle: outdent

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: prefer_alias, prefer_alias_method
Style/Alias:
  Exclude:
    - 'app/controllers/dashboards_controller.rb'
    - 'app/models/device.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedHashRocketStyle, EnforcedColonStyle, EnforcedLastArgumentHashStyle, SupportedLastArgumentHashStyles.
# SupportedLastArgumentHashStyles: always_inspect, always_ignore, ignore_implicit, ignore_explicit
Style/AlignHash:
  Exclude:
    - 'config/initializers/simple_form.rb'

# Offense count: 15
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: with_first_parameter, with_fixed_indentation
Style/AlignParameters:
  Exclude:
    - 'app/models/bgeigie_log.rb'
    - 'app/models/measurement.rb'
    - 'config/initializers/amazon_ses.rb'
    - 'spec/acceptance/user_uploads_bgeigie_log_spec.rb'
    - 'spec/integration/api/bgeigie_imports_spec.rb'
    - 'spec/integration/api/devices_spec.rb'
    - 'spec/integration/api/measurements_spec.rb'

# Offense count: 16
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: always, conditionals
Style/AndOr:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/bgeigie_imports_controller.rb'
    - 'app/models/bgeigie_import.rb'
    - 'config/initializers/carrierwave.rb'
    - 'config/unicorn.rb'

# Offense count: 1
Style/AsciiComments:
  Exclude:
    - 'config/initializers/postgis.rb'

# Offense count: 8
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: percent_q, bare_percent
Style/BarePercentLiterals:
  Exclude:
    - 'app/models/bgeigie_import.rb'
    - 'app/models/drive_import.rb'
    - 'app/models/drive_log.rb'

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ProceduralMethods, FunctionalMethods, IgnoredMethods.
# SupportedStyles: line_count_based, semantic, braces_for_chaining
# ProceduralMethods: benchmark, bm, bmbm, create, each_with_object, measure, new, realtime, tap, with_object
# FunctionalMethods: let, let!, subject, watch
# IgnoredMethods: lambda, proc, it
Style/BlockDelimiters:
  Exclude:
    - 'config/initializers/postgis.rb'
    - 'spec/models/device_spec.rb'
    - 'spec/models/measurement_spec.rb'

# Offense count: 20
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: braces, no_braces, context_dependent
Style/BracesAroundHashParameters:
  Exclude:
    - 'app/models/drive_import.rb'
    - 'spec/integration/api/bgeigie_imports_spec.rb'
    - 'spec/integration/api/devices_spec.rb'
    - 'spec/integration/api/measurements_spec.rb'
    - 'spec/models/device_spec.rb'
    - 'spec/models/measurement_spec.rb'

# Offense count: 3
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'app/helpers/users/sessions_helper.rb'
    - 'app/models/bgeigie_import/state_concerns.rb'
    - 'lib/haml/filters/code.rb'

# Offense count: 4
# Cop supports --auto-correct.
Style/ClosingParenthesisIndentation:
  Exclude:
    - 'spec/integration/api/devices_spec.rb'

# Offense count: 3
# Cop supports --auto-correct.
Style/CommentIndentation:
  Exclude:
    - 'config/initializers/rails_admin.rb'
    - 'config/initializers/wrap_parameters.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, SingleLineConditionsOnly.
# SupportedStyles: assign_to_condition, assign_inside_condition
Style/ConditionalAssignment:
  Exclude:
    - 'app/controllers/application_controller.rb'

# Offense count: 100
Style/Documentation:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: leading, trailing
Style/DotPosition:
  Enabled: false

# Offense count: 3
# Cop supports --auto-correct.
Style/ElseAlignment:
  Exclude:
    - 'app/controllers/measurements_controller.rb'
    - 'app/helpers/bgeigie_imports_helper.rb'
    - 'app/helpers/measurements_helper.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: AllowAdjacentOneLineDefs.
Style/EmptyLineBetweenDefs:
  Exclude:
    - 'app/models/measurement.rb'

# Offense count: 34
# Cop supports --auto-correct.
Style/EmptyLines:
  Exclude:
    - 'app/controllers/bgeigie_imports_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'config/initializers/postgis.rb'
    - 'config/initializers/rails_admin.rb'
    - 'config/routes.rb'
    - 'db/migrate/20111123174941_devise_create_users.rb'
    - 'spec/acceptance/user_views_bgeige_imports_spec.rb'
    - 'spec/helpers/measurements_helper_spec.rb'
    - 'spec/models/bgeigie_import_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/EmptyLinesAroundAccessModifier:
  Exclude:
    - 'app/controllers/bgeigie_imports_controller.rb'

# Offense count: 13
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: empty_lines, no_empty_lines
Style/EmptyLinesAroundBlockBody:
  Exclude:
    - 'config/initializers/intercom.rb'
    - 'config/initializers/rails_admin.rb'
    - 'spec/acceptance/user_submits_reading_spec.rb'
    - 'spec/acceptance/user_views_bgeige_imports_spec.rb'
    - 'spec/controllers/bgeigie_logs_controller_spec.rb'
    - 'spec/integration/api/bgeigie_imports_spec.rb'
    - 'spec/integration/api/devices_spec.rb'
    - 'spec/integration/api/measurements_spec.rb'
    - 'spec/integration/api/users_spec.rb'
    - 'spec/mailers/notifications_spec.rb'
    - 'spec/models/bgeigie_import_spec.rb'

# Offense count: 16
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: empty_lines, no_empty_lines
Style/EmptyLinesAroundClassBody:
  Exclude:
    - 'app/controllers/bgeigie_imports_controller.rb'
    - 'app/controllers/bgeigie_logs_controller.rb'
    - 'app/controllers/devices_controller.rb'
    - 'app/controllers/measurements_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'app/models/bgeigie_import.rb'
    - 'app/models/device.rb'
    - 'app/models/drive_import.rb'
    - 'app/models/drive_log.rb'
    - 'app/uploaders/file_uploader.rb'
    - 'db/migrate/20111123174941_devise_create_users.rb'
    - 'db/migrate/20130114094100_change_height_on_measurement_import_from_integer_to_decimal.rb'

# Offense count: 10
# Cop supports --auto-correct.
Style/EmptyLinesAroundMethodBody:
  Exclude:
    - 'app/models/measurement.rb'
    - 'db/migrate/20120306150302_add_fields_to_measurements.rb'
    - 'db/migrate/20120306202021_add_time_zone_to_user.rb'
    - 'db/migrate/20120307130255_add_status_details_to_measurement_import.rb'
    - 'db/migrate/20120307130803_add_approved_to_measurement_import.rb'
    - 'db/migrate/20120315211955_add_name_and_description_to_measurement_import.rb'
    - 'db/migrate/20120315220809_add_lines_count_to_measurement_import.rb'
    - 'db/migrate/20120417190549_add_details_to_measurement_import.rb'
    - 'db/migrate/20130606042505_add_devise_confirmable_to_user.rb'
    - 'db/migrate/20150919060031_add_extra_fields_to_measurements_table.rb'

# Offense count: 6
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: empty_lines, no_empty_lines
Style/EmptyLinesAroundModuleBody:
  Exclude:
    - 'app/concerns/measurement_concerns.rb'
    - 'app/helpers/bgeigie_imports_helper.rb'
    - 'app/helpers/docs_helper.rb'
    - 'lib/haml/filters/code.rb'

# Offense count: 18
# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment, ForceEqualSignAlignment.
Style/ExtraSpacing:
  Exclude:
    - 'Gemfile'
    - 'app/controllers/measurements_controller.rb'
    - 'app/models/ability.rb'
    - 'config.ru'
    - 'config/environments/test.rb'
    - 'config/initializers/carrierwave.rb'
    - 'script/rails'

# Offense count: 1
Style/GuardClause:
  Exclude:
    - 'app/controllers/application_controller.rb'

# Offense count: 399
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, UseHashRocketsWithSymbolValues.
# SupportedStyles: ruby19, ruby19_no_mixed_keys, hash_rockets
Style/HashSyntax:
  Enabled: false

# Offense count: 8
# Cop supports --auto-correct.
# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/bgeigie_imports_controller.rb'
    - 'app/models/bgeigie_import.rb'
    - 'app/models/device.rb'
    - 'app/views/users/_user.json.jbuilder'
    - 'config/initializers/postgis.rb'

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles, IndentationWidth.
# SupportedStyles: special_inside_parentheses, consistent, align_brackets
Style/IndentArray:
  EnforcedStyle: consistent

# Offense count: 27
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: special_inside_parentheses, consistent, align_braces
Style/IndentHash:
  Enabled: false

# Offense count: 7
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: normal, rails
Style/IndentationConsistency:
  Exclude:
    - 'app/models/device.rb'
    - 'app/models/measurement.rb'
    - 'db/migrate/20130705092519_create_rails_admin_histories_table.rb'

# Offense count: 14
# Cop supports --auto-correct.
# Configuration parameters: Width.
Style/IndentationWidth:
  Exclude:
    - 'app/controllers/measurements_controller.rb'
    - 'app/helpers/bgeigie_imports_helper.rb'
    - 'app/helpers/measurements_helper.rb'
    - 'app/models/device.rb'
    - 'app/models/measurement.rb'
    - 'db/migrate/20120307175658_add_timestamps_to_measurement_imports.rb'
    - 'db/migrate/20130705092519_create_rails_admin_histories_table.rb'
    - 'db/migrate/20150919060031_add_extra_fields_to_measurements_table.rb'
    - 'spec/acceptance/user_views_bgeige_imports_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles.
# SupportedStyles: call, braces
Style/LambdaCall:
  EnforcedStyle: braces

# Offense count: 16
# Cop supports --auto-correct.
Style/LeadingCommentSpace:
  Exclude:
    - 'Gemfile'
    - 'app/controllers/measurements_controller.rb'
    - 'app/models/bgeigie_import.rb'
    - 'app/models/measurement.rb'
    - 'config/routes.rb'
    - 'spec/integration/api/measurements_spec.rb'
    - 'spec/models/bgeigie_import_spec.rb'

# Offense count: 3
# Cop supports --auto-correct.
Style/MultilineBlockLayout:
  Exclude:
    - 'spec/models/device_spec.rb'
    - 'spec/models/measurement_spec.rb'

# Offense count: 7
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: symmetrical, new_line, same_line
Style/MultilineMethodCallBraceLayout:
  Exclude:
    - 'app/mailers/notifications.rb'
    - 'spec/integration/api/devices_spec.rb'
    - 'spec/models/bgeigie_import_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: aligned, indented
Style/MultilineMethodCallIndentation:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Style/NegatedIf:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/dashboards_controller.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/NilComparison:
  Exclude:
    - 'spec/acceptance/user_submits_reading_spec.rb'
    - 'spec/integration/api/users_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 6

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Exclude:
    - 'app/models/bgeigie_import.rb'
    - 'app/models/drive_log.rb'
    - 'lib/tasks/boostrap.rake'
    - 'lib/tasks/watchr.rake'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: lower_case_q, upper_case_q
Style/PercentQLiterals:
  Exclude:
    - 'app/models/bgeigie_import.rb'

# Offense count: 1
# Configuration parameters: NamePrefix, NamePrefixBlacklist, NameWhitelist.
# NamePrefix: is_, has_, have_
# NamePrefixBlacklist: is_, has_, have_
# NameWhitelist: is_a?
Style/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'app/models/bgeigie_import.rb'

# Offense count: 45
# Cop supports --auto-correct.
Style/RedundantSelf:
  Exclude:
    - 'app/models/bgeigie_import.rb'
    - 'app/models/device.rb'
    - 'app/models/drive_import.rb'
    - 'app/models/drive_log.rb'
    - 'app/models/measurement.rb'
    - 'app/uploaders/file_uploader.rb'
    - 'lib/extras/simple_form_extensions.rb'

# Offense count: 6
# Cop supports --auto-correct.
Style/RescueModifier:
  Exclude:
    - 'app/models/bgeigie_import.rb'
    - 'app/models/drive_import.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowAsExpressionSeparator.
Style/Semicolon:
  Exclude:
    - 'spec/integration/api/bgeigie_imports_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: only_raise, only_fail, semantic
Style/SignalException:
  Exclude:
    - 'lib/tasks/boostrap.rake'

# Offense count: 4
# Cop supports --auto-correct.
Style/SpaceAfterComma:
  Exclude:
    - 'spec/integration/api/bgeigie_imports_spec.rb'
    - 'spec/integration/api/measurements_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: space, no_space
Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

# Offense count: 7
# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment.
Style/SpaceAroundOperators:
  Exclude:
    - 'app/controllers/measurements_controller.rb'
    - 'app/models/bgeigie_log.rb'
    - 'config/environments/test.rb'
    - 'config/initializers/carrierwave.rb'
    - 'db/migrate/20120521225350_add_spatial_index_on_measurements.rb'
    - 'spec/integration/api/devices_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: space, no_space
Style/SpaceBeforeBlockBraces:
  Enabled: false

# Offense count: 8
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, EnforcedStyleForEmptyBraces, SpaceBeforeBlockParameters.
# SupportedStyles: space, no_space
Style/SpaceInsideBlockBraces:
  Enabled: false

# Offense count: 6
# Cop supports --auto-correct.
Style/SpaceInsideBrackets:
  Exclude:
    - 'config/initializers/devise.rb'
    - 'db/migrate/20160208190731_add_subtype_to_measurement_imports.rb'

# Offense count: 13
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
# SupportedStyles: space, no_space
Style/SpaceInsideHashLiteralBraces:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/SpaceInsideParens:
  Exclude:
    - 'db/migrate/20130705092519_create_rails_admin_histories_table.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles.
# SupportedStyles: use_perl_names, use_english_names
Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

# Offense count: 181
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
# IgnoredMethods: respond_to, define_method
Style/SymbolProc:
  Exclude:
    - 'app/models/drive_import.rb'
    - 'db/migrate/20120307175658_add_timestamps_to_measurement_imports.rb'
    - 'spec/models/bgeigie_import_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/Tab:
  Exclude:
    - 'db/migrate/20111214154833_create_delayed_jobs.rb'

# Offense count: 37
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: final_newline, final_blank_line
Style/TrailingBlankLines:
  Enabled: false

# Offense count: 330
# Cop supports --auto-correct.
Style/TrailingWhitespace:
  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
Style/UnneededInterpolation:
  Exclude:
    - 'app/helpers/measurements_helper.rb'
    - 'app/models/drive_import.rb'
    - 'config/unicorn.rb'

# Offense count: 6
# Cop supports --auto-correct.
Style/UnneededPercentQ:
  Exclude:
    - 'app/models/bgeigie_import.rb'
    - 'app/models/drive_import.rb'

# Offense count: 2
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: snake_case, camelCase
Style/VariableName:
  Enabled: false

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles, WordRegex.
# SupportedStyles: percent, brackets
Style/WordArray:
  EnforcedStyle: percent
  MinSize: 4
