language: ruby
rvm:
  - 1.9.3
#services: postgis
before_install:
  - sudo apt-get install -qq postgis
before_script:
  - createuser -s safecast;
  - psql -c 'create database safecast_test;' -U postgres
  - 
