language: ruby
rvm:
  - 1.9.3
before_install:
  - sudo apt-get install -qq postgis
  - createuser -s safecast
  - psql -c 'create database safecast_test;' -U postgres
  - pg_share=$(pg_config --sharedir)
  - psql -d safecast_test -f $pg_share/contrib/postgis-1.5/postgis.sql -q
  - psql -d safecast_test -f $pg_share/contrib/postgis-1.5/spatial_ref_sys.sql -q
