sudo: false
language: ruby
rvm:
  - 1.9.3
addons:
    postgresql: "9.2"
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -U postgres -c 'create database travis_ci_test'
  - psql -U postgres -c 'create extension postgis' travis_ci_test
script:
  - bundle exec rake db:schema:load
  - bundle exec rspec spec
