language: ruby
rvm:
  - 1.9.3
before_install:
  - sudo apt-get install -qq postgis postgresql-9.1-postgis
before_script:
  - createuser -s safecast
  - psql -c 'create database safecast_test;' -U postgres
  - rake db:migrate
  - rake db:test:prepare
script: bundle exec rspec spec
